# Generated by Django 3.1.1 on 2020-09-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='puplish_date',
            new_name='publish_date',
        ),
    ]
